//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegurosDeVida
    {
        public int IdSeguroVida { get; set; }
        public int IdSeguro { get; set; }
    
        public virtual TipoSeguro TipoSeguro { get; set; }
    }
}
