//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSeguro
    {
        public TipoSeguro()
        {
            this.BienesInmuebles = new HashSet<BienesInmuebles>();
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
            this.SegurosDeVida = new HashSet<SegurosDeVida>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int IdSeguro { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<BienesInmuebles> BienesInmuebles { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
        public virtual ICollection<SegurosDeVida> SegurosDeVida { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
